name: vae-dgm-cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch-cpu>=1.9.0
  - torchvision-cpu>=0.10.0
  - matplotlib>=3.3.0
  - numpy>=1.19.0
  - pip
  - pip:
    - medmnist>=2.1.0
    - torchmetrics>=0.7.0 