name: vae-dgm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - cudatoolkit=11.3  # Only if you have CUDA GPU
  - matplotlib>=3.3.0
  - numpy>=1.19.0
  - pip
  - pip:
    - medmnist>=2.1.0
    - torchmetrics>=0.7.0 